# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VBUI.ui'
#
# Created: Mon May 25 14:02:04 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_frmVirusBattle(object):
    def setupUi(self, frmVirusBattle):
        frmVirusBattle.setObjectName("frmVirusBattle")
        frmVirusBattle.setWindowModality(QtCore.Qt.ApplicationModal)
        frmVirusBattle.resize(752, 459)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmVirusBattle.sizePolicy().hasHeightForWidth())
        frmVirusBattle.setSizePolicy(sizePolicy)
        self.toolBox = QtGui.QToolBox(frmVirusBattle)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 731, 391))
        self.toolBox.setFrameShadow(QtGui.QFrame.Raised)
        self.toolBox.setObjectName("toolBox")
        self.pageConfiguration = QtGui.QWidget()
        self.pageConfiguration.setGeometry(QtCore.QRect(0, 0, 731, 310))
        self.pageConfiguration.setObjectName("pageConfiguration")
        self.groupBox = QtGui.QGroupBox(self.pageConfiguration)
        self.groupBox.setGeometry(QtCore.QRect(0, 180, 201, 101))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 31, 20))
        self.label_2.setObjectName("label_2")
        self.btnRegister = QtGui.QPushButton(self.groupBox)
        self.btnRegister.setEnabled(True)
        self.btnRegister.setGeometry(QtCore.QRect(140, 73, 51, 23))
        self.btnRegister.setObjectName("btnRegister")
        self.editName = QtGui.QLineEdit(self.groupBox)
        self.editName.setGeometry(QtCore.QRect(50, 50, 141, 20))
        self.editName.setObjectName("editName")
        self.editEmail = QtGui.QLineEdit(self.groupBox)
        self.editEmail.setGeometry(QtCore.QRect(50, 20, 141, 20))
        self.editEmail.setObjectName("editEmail")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 30, 20))
        self.label.setObjectName("label")
        self.groupBox_3 = QtGui.QGroupBox(self.pageConfiguration)
        self.groupBox_3.setGeometry(QtCore.QRect(480, 0, 191, 281))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 12, 91, 20))
        self.label_8.setObjectName("label_8")
        self.listProfiles = QtGui.QListWidget(self.groupBox_3)
        self.listProfiles.setGeometry(QtCore.QRect(10, 30, 171, 121))
        self.listProfiles.setObjectName("listProfiles")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 101, 20))
        self.label_3.setObjectName("label_3")
        self.editProfileName = QtGui.QLineEdit(self.groupBox_3)
        self.editProfileName.setGeometry(QtCore.QRect(10, 220, 171, 20))
        self.editProfileName.setText("")
        self.editProfileName.setObjectName("editProfileName")
        self.btnSaveProfile = QtGui.QPushButton(self.groupBox_3)
        self.btnSaveProfile.setGeometry(QtCore.QRect(120, 250, 61, 23))
        self.btnSaveProfile.setAutoDefault(False)
        self.btnSaveProfile.setDefault(False)
        self.btnSaveProfile.setFlat(False)
        self.btnSaveProfile.setObjectName("btnSaveProfile")
        self.btnRemoveProfile = QtGui.QPushButton(self.groupBox_3)
        self.btnRemoveProfile.setEnabled(False)
        self.btnRemoveProfile.setGeometry(QtCore.QRect(130, 160, 51, 23))
        self.btnRemoveProfile.setAutoDefault(False)
        self.btnRemoveProfile.setDefault(False)
        self.btnRemoveProfile.setFlat(False)
        self.btnRemoveProfile.setObjectName("btnRemoveProfile")
        self.btnExportProfile = QtGui.QPushButton(self.groupBox_3)
        self.btnExportProfile.setEnabled(True)
        self.btnExportProfile.setGeometry(QtCore.QRect(70, 160, 51, 23))
        self.btnExportProfile.setAutoDefault(False)
        self.btnExportProfile.setDefault(False)
        self.btnExportProfile.setFlat(False)
        self.btnExportProfile.setObjectName("btnExportProfile")
        self.btnImportProfile = QtGui.QPushButton(self.groupBox_3)
        self.btnImportProfile.setEnabled(True)
        self.btnImportProfile.setGeometry(QtCore.QRect(10, 160, 51, 23))
        self.btnImportProfile.setAutoDefault(False)
        self.btnImportProfile.setDefault(False)
        self.btnImportProfile.setFlat(False)
        self.btnImportProfile.setObjectName("btnImportProfile")
        self.groupBox_8 = QtGui.QGroupBox(self.pageConfiguration)
        self.groupBox_8.setGeometry(QtCore.QRect(210, 150, 261, 131))
        self.groupBox_8.setObjectName("groupBox_8")
        self.editHighlightCaption = QtGui.QTextEdit(self.groupBox_8)
        self.editHighlightCaption.setGeometry(QtCore.QRect(10, 53, 241, 41))
        self.editHighlightCaption.setObjectName("editHighlightCaption")
        self.label_6 = QtGui.QLabel(self.groupBox_8)
        self.label_6.setGeometry(QtCore.QRect(10, 29, 91, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setGeometry(QtCore.QRect(10, 99, 91, 20))
        self.label_7.setObjectName("label_7")
        self.btnHighlightColorChooser = QtGui.QPushButton(self.groupBox_8)
        self.btnHighlightColorChooser.setGeometry(QtCore.QRect(90, 99, 21, 21))
        self.btnHighlightColorChooser.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.btnHighlightColorChooser.setObjectName("btnHighlightColorChooser")
        self.btnRemoveHighlights = QtGui.QPushButton(self.groupBox_8)
        self.btnRemoveHighlights.setGeometry(QtCore.QRect(150, 16, 101, 23))
        self.btnRemoveHighlights.setAutoDefault(False)
        self.btnRemoveHighlights.setDefault(False)
        self.btnRemoveHighlights.setFlat(False)
        self.btnRemoveHighlights.setObjectName("btnRemoveHighlights")
        self.groupBox_7 = QtGui.QGroupBox(self.pageConfiguration)
        self.groupBox_7.setGeometry(QtCore.QRect(210, 0, 261, 141))
        self.groupBox_7.setObjectName("groupBox_7")
        self.checkUpperHalf = QtGui.QCheckBox(self.groupBox_7)
        self.checkUpperHalf.setGeometry(QtCore.QRect(10, 114, 101, 17))
        self.checkUpperHalf.setObjectName("checkUpperHalf")
        self.checkNoLibProc = QtGui.QCheckBox(self.groupBox_7)
        self.checkNoLibProc.setGeometry(QtCore.QRect(100, 114, 201, 20))
        self.checkNoLibProc.setObjectName("checkNoLibProc")
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 84, 91, 20))
        self.label_9.setObjectName("label_9")
        self.boxThreshold = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.boxThreshold.setGeometry(QtCore.QRect(70, 84, 62, 22))
        self.boxThreshold.setMaximum(1.0)
        self.boxThreshold.setSingleStep(0.1)
        self.boxThreshold.setProperty("value", 0.5)
        self.boxThreshold.setObjectName("boxThreshold")
        self.label_5 = QtGui.QLabel(self.groupBox_7)
        self.label_5.setGeometry(QtCore.QRect(10, 13, 51, 20))
        self.label_5.setObjectName("label_5")
        self.editAPIKey = QtGui.QLineEdit(self.groupBox_7)
        self.editAPIKey.setGeometry(QtCore.QRect(10, 32, 241, 20))
        self.editAPIKey.setText("")
        self.editAPIKey.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.editAPIKey.setObjectName("editAPIKey")
        self.btnShowAPIKey = QtGui.QPushButton(self.groupBox_7)
        self.btnShowAPIKey.setGeometry(QtCore.QRect(210, 60, 41, 23))
        self.btnShowAPIKey.setAutoDefault(False)
        self.btnShowAPIKey.setDefault(False)
        self.btnShowAPIKey.setFlat(False)
        self.btnShowAPIKey.setObjectName("btnShowAPIKey")
        self.browserAboutUs = QtGui.QTextBrowser(self.pageConfiguration)
        self.browserAboutUs.setGeometry(QtCore.QRect(0, 20, 201, 151))
        self.browserAboutUs.setOpenExternalLinks(True)
        self.browserAboutUs.setObjectName("browserAboutUs")
        self.label_41 = QtGui.QLabel(self.pageConfiguration)
        self.label_41.setGeometry(QtCore.QRect(0, 0, 51, 20))
        self.label_41.setObjectName("label_41")
        self.toolBox.addItem(self.pageConfiguration, "")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 731, 310))
        self.page.setObjectName("page")
        self.tabWidgetVB = QtGui.QTabWidget(self.page)
        self.tabWidgetVB.setGeometry(QtCore.QRect(0, 0, 731, 311))
        self.tabWidgetVB.setObjectName("tabWidgetVB")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_10.setObjectName("label_10")
        self.listBins = QtGui.QListWidget(self.tab_2)
        self.listBins.setGeometry(QtCore.QRect(10, 30, 131, 211))
        self.listBins.setObjectName("listBins")
        self.groupBinary = QtGui.QGroupBox(self.tab_2)
        self.groupBinary.setEnabled(True)
        self.groupBinary.setGeometry(QtCore.QRect(150, 10, 301, 271))
        self.groupBinary.setObjectName("groupBinary")
        self.listChildren = QtGui.QListWidget(self.groupBinary)
        self.listChildren.setGeometry(QtCore.QRect(80, 200, 131, 61))
        self.listChildren.setObjectName("listChildren")
        self.editSHA = QtGui.QTextEdit(self.groupBinary)
        self.editSHA.setGeometry(QtCore.QRect(80, 50, 211, 21))
        self.editSHA.setReadOnly(True)
        self.editSHA.setObjectName("editSHA")
        self.label_15 = QtGui.QLabel(self.groupBinary)
        self.label_15.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.label_15.setObjectName("label_15")
        self.editFileLength = QtGui.QLineEdit(self.groupBinary)
        self.editFileLength.setEnabled(True)
        self.editFileLength.setGeometry(QtCore.QRect(230, 170, 61, 20))
        self.editFileLength.setText("")
        self.editFileLength.setReadOnly(True)
        self.editFileLength.setObjectName("editFileLength")
        self.label_12 = QtGui.QLabel(self.groupBinary)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 46, 13))
        self.label_12.setObjectName("label_12")
        self.editFileType = QtGui.QTextEdit(self.groupBinary)
        self.editFileType.setGeometry(QtCore.QRect(80, 80, 211, 21))
        self.editFileType.setReadOnly(True)
        self.editFileType.setObjectName("editFileType")
        self.label_16 = QtGui.QLabel(self.groupBinary)
        self.label_16.setGeometry(QtCore.QRect(10, 140, 91, 16))
        self.label_16.setObjectName("label_16")
        self.editUploadedDate = QtGui.QLineEdit(self.groupBinary)
        self.editUploadedDate.setEnabled(True)
        self.editUploadedDate.setGeometry(QtCore.QRect(80, 170, 101, 20))
        self.editUploadedDate.setText("")
        self.editUploadedDate.setReadOnly(True)
        self.editUploadedDate.setObjectName("editUploadedDate")
        self.editMD5 = QtGui.QLineEdit(self.groupBinary)
        self.editMD5.setEnabled(True)
        self.editMD5.setGeometry(QtCore.QRect(80, 110, 211, 20))
        self.editMD5.setText("")
        self.editMD5.setReadOnly(True)
        self.editMD5.setObjectName("editMD5")
        self.label_13 = QtGui.QLabel(self.groupBinary)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_13.setObjectName("label_13")
        self.btnDownloadBinary = QtGui.QPushButton(self.groupBinary)
        self.btnDownloadBinary.setEnabled(False)
        self.btnDownloadBinary.setGeometry(QtCore.QRect(230, 210, 61, 23))
        self.btnDownloadBinary.setObjectName("btnDownloadBinary")
        self.label_17 = QtGui.QLabel(self.groupBinary)
        self.label_17.setGeometry(QtCore.QRect(10, 200, 131, 16))
        self.label_17.setObjectName("label_17")
        self.label_14 = QtGui.QLabel(self.groupBinary)
        self.label_14.setGeometry(QtCore.QRect(190, 170, 46, 13))
        self.label_14.setObjectName("label_14")
        self.btnRefreshBinary = QtGui.QPushButton(self.groupBinary)
        self.btnRefreshBinary.setEnabled(False)
        self.btnRefreshBinary.setGeometry(QtCore.QRect(230, 240, 61, 23))
        self.btnRefreshBinary.setObjectName("btnRefreshBinary")
        self.label_11 = QtGui.QLabel(self.groupBinary)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_11.setObjectName("label_11")
        self.editClassObject = QtGui.QTextEdit(self.groupBinary)
        self.editClassObject.setGeometry(QtCore.QRect(80, 140, 211, 21))
        self.editClassObject.setReadOnly(True)
        self.editClassObject.setObjectName("editClassObject")
        self.editOrigFilePath = QtGui.QTextEdit(self.groupBinary)
        self.editOrigFilePath.setGeometry(QtCore.QRect(80, 20, 211, 21))
        self.editOrigFilePath.setReadOnly(True)
        self.editOrigFilePath.setObjectName("editOrigFilePath")
        self.label_25 = QtGui.QLabel(self.groupBinary)
        self.label_25.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_25.setObjectName("label_25")
        self.groupChild = QtGui.QGroupBox(self.tab_2)
        self.groupChild.setEnabled(True)
        self.groupChild.setGeometry(QtCore.QRect(460, 10, 251, 271))
        self.groupChild.setObjectName("groupChild")
        self.editChildServiceName = QtGui.QLineEdit(self.groupChild)
        self.editChildServiceName.setEnabled(True)
        self.editChildServiceName.setGeometry(QtCore.QRect(90, 77, 151, 20))
        self.editChildServiceName.setText("")
        self.editChildServiceName.setReadOnly(True)
        self.editChildServiceName.setObjectName("editChildServiceName")
        self.label_18 = QtGui.QLabel(self.groupChild)
        self.label_18.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.groupChild)
        self.label_19.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_19.setObjectName("label_19")
        self.editChildStatus = QtGui.QLineEdit(self.groupChild)
        self.editChildStatus.setEnabled(True)
        self.editChildStatus.setGeometry(QtCore.QRect(90, 107, 151, 20))
        self.editChildStatus.setText("")
        self.editChildStatus.setReadOnly(True)
        self.editChildStatus.setObjectName("editChildStatus")
        self.label_20 = QtGui.QLabel(self.groupChild)
        self.label_20.setGeometry(QtCore.QRect(10, 23, 101, 16))
        self.label_20.setObjectName("label_20")
        self.editChildHash = QtGui.QLineEdit(self.groupChild)
        self.editChildHash.setEnabled(True)
        self.editChildHash.setGeometry(QtCore.QRect(10, 40, 231, 20))
        self.editChildHash.setText("")
        self.editChildHash.setReadOnly(True)
        self.editChildHash.setObjectName("editChildHash")
        self.groupBox_10 = QtGui.QGroupBox(self.groupChild)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 130, 231, 101))
        self.groupBox_10.setObjectName("groupBox_10")
        self.editChildUnpackerMessage = QtGui.QTextEdit(self.groupBox_10)
        self.editChildUnpackerMessage.setGeometry(QtCore.QRect(70, 50, 151, 41))
        self.editChildUnpackerMessage.setReadOnly(True)
        self.editChildUnpackerMessage.setObjectName("editChildUnpackerMessage")
        self.label_21 = QtGui.QLabel(self.groupChild)
        self.label_21.setGeometry(QtCore.QRect(20, 180, 101, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.groupChild)
        self.label_22.setGeometry(QtCore.QRect(20, 150, 101, 16))
        self.label_22.setObjectName("label_22")
        self.editChildUnpackerTime = QtGui.QLineEdit(self.groupChild)
        self.editChildUnpackerTime.setEnabled(True)
        self.editChildUnpackerTime.setGeometry(QtCore.QRect(80, 150, 51, 20))
        self.editChildUnpackerTime.setText("")
        self.editChildUnpackerTime.setReadOnly(True)
        self.editChildUnpackerTime.setObjectName("editChildUnpackerTime")
        self.btnDownloadChildBinary = QtGui.QPushButton(self.groupChild)
        self.btnDownloadChildBinary.setEnabled(False)
        self.btnDownloadChildBinary.setGeometry(QtCore.QRect(180, 240, 61, 23))
        self.btnDownloadChildBinary.setObjectName("btnDownloadChildBinary")
        self.btnShowChild = QtGui.QPushButton(self.groupChild)
        self.btnShowChild.setEnabled(True)
        self.btnShowChild.setGeometry(QtCore.QRect(10, 240, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.btnShowChild.setFont(font)
        self.btnShowChild.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.btnShowChild.setText("")
        self.btnShowChild.setFlat(False)
        self.btnShowChild.setObjectName("btnShowChild")
        self.btnReloadBinaries = QtGui.QPushButton(self.tab_2)
        self.btnReloadBinaries.setGeometry(QtCore.QRect(90, 250, 51, 23))
        self.btnReloadBinaries.setObjectName("btnReloadBinaries")
        self.lcdUploadedBins = QtGui.QLCDNumber(self.tab_2)
        self.lcdUploadedBins.setGeometry(QtCore.QRect(30, 250, 61, 23))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.lcdUploadedBins.setFont(font)
        self.lcdUploadedBins.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdUploadedBins.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdUploadedBins.setLineWidth(1)
        self.lcdUploadedBins.setSmallDecimalPoint(True)
        self.lcdUploadedBins.setDigitCount(6)
        self.lcdUploadedBins.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdUploadedBins.setProperty("value", 0.0)
        self.lcdUploadedBins.setObjectName("lcdUploadedBins")
        self.label_42 = QtGui.QLabel(self.tab_2)
        self.label_42.setGeometry(QtCore.QRect(10, 254, 46, 13))
        self.label_42.setObjectName("label_42")
        self.tabWidgetVB.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_23.setObjectName("label_23")
        self.listMatchedBins = QtGui.QListWidget(self.tab)
        self.listMatchedBins.setGeometry(QtCore.QRect(10, 30, 131, 51))
        self.listMatchedBins.setObjectName("listMatchedBins")
        self.groupBinary_2 = QtGui.QGroupBox(self.tab)
        self.groupBinary_2.setEnabled(True)
        self.groupBinary_2.setGeometry(QtCore.QRect(10, 120, 131, 131))
        self.groupBinary_2.setObjectName("groupBinary_2")
        self.label_26 = QtGui.QLabel(self.groupBinary_2)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_26.setObjectName("label_26")
        self.editMatchedBinSHA = QtGui.QTextEdit(self.groupBinary_2)
        self.editMatchedBinSHA.setGeometry(QtCore.QRect(10, 40, 111, 31))
        self.editMatchedBinSHA.setReadOnly(True)
        self.editMatchedBinSHA.setObjectName("editMatchedBinSHA")
        self.label_27 = QtGui.QLabel(self.groupBinary_2)
        self.label_27.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_27.setObjectName("label_27")
        self.lcdSimilarity = QtGui.QLCDNumber(self.groupBinary_2)
        self.lcdSimilarity.setGeometry(QtCore.QRect(60, 77, 64, 23))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.lcdSimilarity.setFont(font)
        self.lcdSimilarity.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdSimilarity.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdSimilarity.setLineWidth(1)
        self.lcdSimilarity.setSmallDecimalPoint(True)
        self.lcdSimilarity.setDigitCount(6)
        self.lcdSimilarity.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdSimilarity.setProperty("value", 0.0)
        self.lcdSimilarity.setObjectName("lcdSimilarity")
        self.btnDownloadMatchedBin = QtGui.QPushButton(self.groupBinary_2)
        self.btnDownloadMatchedBin.setEnabled(False)
        self.btnDownloadMatchedBin.setGeometry(QtCore.QRect(60, 100, 61, 23))
        self.btnDownloadMatchedBin.setObjectName("btnDownloadMatchedBin")
        self.lblOpenFileHash = QtGui.QLabel(self.tab)
        self.lblOpenFileHash.setGeometry(QtCore.QRect(10, 270, 511, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.lblOpenFileHash.setFont(font)
        self.lblOpenFileHash.setObjectName("lblOpenFileHash")
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(300, 10, 201, 261))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(10, 22, 46, 13))
        self.label_29.setObjectName("label_29")
        self.editMatchedLeftBinID = QtGui.QTextEdit(self.groupBox_4)
        self.editMatchedLeftBinID.setGeometry(QtCore.QRect(10, 37, 181, 31))
        self.editMatchedLeftBinID.setReadOnly(True)
        self.editMatchedLeftBinID.setObjectName("editMatchedLeftBinID")
        self.label_31 = QtGui.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(10, 107, 46, 13))
        self.label_31.setObjectName("label_31")
        self.editMatchedLeftProcName = QtGui.QLineEdit(self.groupBox_4)
        self.editMatchedLeftProcName.setEnabled(True)
        self.editMatchedLeftProcName.setGeometry(QtCore.QRect(90, 107, 101, 20))
        self.editMatchedLeftProcName.setText("")
        self.editMatchedLeftProcName.setReadOnly(True)
        self.editMatchedLeftProcName.setObjectName("editMatchedLeftProcName")
        self.editMatchedLeftProcRVA = QtGui.QLineEdit(self.groupBox_4)
        self.editMatchedLeftProcRVA.setEnabled(True)
        self.editMatchedLeftProcRVA.setGeometry(QtCore.QRect(90, 77, 101, 20))
        self.editMatchedLeftProcRVA.setText("")
        self.editMatchedLeftProcRVA.setReadOnly(True)
        self.editMatchedLeftProcRVA.setObjectName("editMatchedLeftProcRVA")
        self.label_33 = QtGui.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(10, 77, 31, 16))
        self.label_33.setObjectName("label_33")
        self.checkMatchedLeftProcIsThunk = QtGui.QCheckBox(self.groupBox_4)
        self.checkMatchedLeftProcIsThunk.setEnabled(True)
        self.checkMatchedLeftProcIsThunk.setGeometry(QtCore.QRect(10, 230, 71, 20))
        self.checkMatchedLeftProcIsThunk.setCheckable(False)
        self.checkMatchedLeftProcIsThunk.setObjectName("checkMatchedLeftProcIsThunk")
        self.label_34 = QtGui.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(10, 170, 61, 16))
        self.label_34.setObjectName("label_34")
        self.editMatchedLeftProcCodeSize = QtGui.QLineEdit(self.groupBox_4)
        self.editMatchedLeftProcCodeSize.setEnabled(True)
        self.editMatchedLeftProcCodeSize.setGeometry(QtCore.QRect(90, 167, 51, 20))
        self.editMatchedLeftProcCodeSize.setText("")
        self.editMatchedLeftProcCodeSize.setReadOnly(True)
        self.editMatchedLeftProcCodeSize.setObjectName("editMatchedLeftProcCodeSize")
        self.checkMatchedLeftProcIsLib = QtGui.QCheckBox(self.groupBox_4)
        self.checkMatchedLeftProcIsLib.setGeometry(QtCore.QRect(70, 230, 71, 17))
        self.checkMatchedLeftProcIsLib.setCheckable(False)
        self.checkMatchedLeftProcIsLib.setObjectName("checkMatchedLeftProcIsLib")
        self.label_35 = QtGui.QLabel(self.groupBox_4)
        self.label_35.setGeometry(QtCore.QRect(10, 137, 61, 16))
        self.label_35.setObjectName("label_35")
        self.editMatchedLeftProcSegment = QtGui.QLineEdit(self.groupBox_4)
        self.editMatchedLeftProcSegment.setEnabled(True)
        self.editMatchedLeftProcSegment.setGeometry(QtCore.QRect(90, 137, 101, 20))
        self.editMatchedLeftProcSegment.setText("")
        self.editMatchedLeftProcSegment.setReadOnly(True)
        self.editMatchedLeftProcSegment.setObjectName("editMatchedLeftProcSegment")
        self.editMatchedLeftProcSemSize = QtGui.QLineEdit(self.groupBox_4)
        self.editMatchedLeftProcSemSize.setEnabled(True)
        self.editMatchedLeftProcSemSize.setGeometry(QtCore.QRect(90, 197, 51, 20))
        self.editMatchedLeftProcSemSize.setText("")
        self.editMatchedLeftProcSemSize.setReadOnly(True)
        self.editMatchedLeftProcSemSize.setObjectName("editMatchedLeftProcSemSize")
        self.label_36 = QtGui.QLabel(self.groupBox_4)
        self.label_36.setGeometry(QtCore.QRect(10, 197, 71, 16))
        self.label_36.setObjectName("label_36")
        self.btnMatchedLeftProcMoreInfo = QtGui.QPushButton(self.groupBox_4)
        self.btnMatchedLeftProcMoreInfo.setEnabled(True)
        self.btnMatchedLeftProcMoreInfo.setGeometry(QtCore.QRect(170, 10, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.btnMatchedLeftProcMoreInfo.setFont(font)
        self.btnMatchedLeftProcMoreInfo.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.btnMatchedLeftProcMoreInfo.setText("")
        self.btnMatchedLeftProcMoreInfo.setFlat(False)
        self.btnMatchedLeftProcMoreInfo.setObjectName("btnMatchedLeftProcMoreInfo")
        self.btnReloadSimilarBins = QtGui.QPushButton(self.tab)
        self.btnReloadSimilarBins.setEnabled(True)
        self.btnReloadSimilarBins.setGeometry(QtCore.QRect(80, 90, 61, 23))
        self.btnReloadSimilarBins.setObjectName("btnReloadSimilarBins")
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(510, 10, 201, 261))
        self.groupBox_5.setObjectName("groupBox_5")
        self.checkMatchedRightProcIsThunk = QtGui.QCheckBox(self.groupBox_5)
        self.checkMatchedRightProcIsThunk.setGeometry(QtCore.QRect(10, 230, 71, 20))
        self.checkMatchedRightProcIsThunk.setCheckable(False)
        self.checkMatchedRightProcIsThunk.setObjectName("checkMatchedRightProcIsThunk")
        self.checkMatchedRightProcIsLib = QtGui.QCheckBox(self.groupBox_5)
        self.checkMatchedRightProcIsLib.setGeometry(QtCore.QRect(70, 230, 71, 17))
        self.checkMatchedRightProcIsLib.setCheckable(False)
        self.checkMatchedRightProcIsLib.setObjectName("checkMatchedRightProcIsLib")
        self.editMatchedRightProcSemSize = QtGui.QLineEdit(self.groupBox_5)
        self.editMatchedRightProcSemSize.setEnabled(True)
        self.editMatchedRightProcSemSize.setGeometry(QtCore.QRect(90, 200, 51, 20))
        self.editMatchedRightProcSemSize.setText("")
        self.editMatchedRightProcSemSize.setReadOnly(True)
        self.editMatchedRightProcSemSize.setObjectName("editMatchedRightProcSemSize")
        self.label_39 = QtGui.QLabel(self.groupBox_5)
        self.label_39.setGeometry(QtCore.QRect(10, 202, 71, 16))
        self.label_39.setObjectName("label_39")
        self.btnMatchedRightProcMoreInfo = QtGui.QPushButton(self.groupBox_5)
        self.btnMatchedRightProcMoreInfo.setEnabled(True)
        self.btnMatchedRightProcMoreInfo.setGeometry(QtCore.QRect(170, 10, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.btnMatchedRightProcMoreInfo.setFont(font)
        self.btnMatchedRightProcMoreInfo.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.btnMatchedRightProcMoreInfo.setText("")
        self.btnMatchedRightProcMoreInfo.setFlat(False)
        self.btnMatchedRightProcMoreInfo.setObjectName("btnMatchedRightProcMoreInfo")
        self.editMatchedRightBinID = QtGui.QTextEdit(self.tab)
        self.editMatchedRightBinID.setGeometry(QtCore.QRect(520, 50, 181, 31))
        self.editMatchedRightBinID.setReadOnly(True)
        self.editMatchedRightBinID.setObjectName("editMatchedRightBinID")
        self.label_37 = QtGui.QLabel(self.tab)
        self.label_37.setGeometry(QtCore.QRect(520, 182, 61, 16))
        self.label_37.setObjectName("label_37")
        self.editMatchedRightProcName = QtGui.QLineEdit(self.tab)
        self.editMatchedRightProcName.setEnabled(True)
        self.editMatchedRightProcName.setGeometry(QtCore.QRect(600, 120, 101, 20))
        self.editMatchedRightProcName.setText("")
        self.editMatchedRightProcName.setReadOnly(True)
        self.editMatchedRightProcName.setObjectName("editMatchedRightProcName")
        self.label_38 = QtGui.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(520, 90, 31, 16))
        self.label_38.setObjectName("label_38")
        self.editMatchedRightProcSegment = QtGui.QLineEdit(self.tab)
        self.editMatchedRightProcSegment.setEnabled(True)
        self.editMatchedRightProcSegment.setGeometry(QtCore.QRect(600, 150, 101, 20))
        self.editMatchedRightProcSegment.setText("")
        self.editMatchedRightProcSegment.setReadOnly(True)
        self.editMatchedRightProcSegment.setObjectName("editMatchedRightProcSegment")
        self.editMatchedRightProcRVA = QtGui.QLineEdit(self.tab)
        self.editMatchedRightProcRVA.setEnabled(True)
        self.editMatchedRightProcRVA.setGeometry(QtCore.QRect(600, 90, 101, 20))
        self.editMatchedRightProcRVA.setText("")
        self.editMatchedRightProcRVA.setReadOnly(True)
        self.editMatchedRightProcRVA.setObjectName("editMatchedRightProcRVA")
        self.label_40 = QtGui.QLabel(self.tab)
        self.label_40.setGeometry(QtCore.QRect(520, 150, 61, 16))
        self.label_40.setObjectName("label_40")
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(520, 120, 46, 13))
        self.label_32.setObjectName("label_32")
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(520, 35, 46, 13))
        self.label_30.setObjectName("label_30")
        self.editMatchedRightProcCodeSize = QtGui.QLineEdit(self.tab)
        self.editMatchedRightProcCodeSize.setEnabled(True)
        self.editMatchedRightProcCodeSize.setGeometry(QtCore.QRect(600, 180, 51, 20))
        self.editMatchedRightProcCodeSize.setText("")
        self.editMatchedRightProcCodeSize.setReadOnly(True)
        self.editMatchedRightProcCodeSize.setObjectName("editMatchedRightProcCodeSize")
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(150, 10, 141, 261))
        self.groupBox_6.setObjectName("groupBox_6")
        self.listProcsWithSim = QtGui.QListWidget(self.groupBox_6)
        self.listProcsWithSim.setGeometry(QtCore.QRect(10, 20, 121, 81))
        self.listProcsWithSim.setObjectName("listProcsWithSim")
        self.lcdMatchedProcs = QtGui.QLCDNumber(self.groupBox_6)
        self.lcdMatchedProcs.setGeometry(QtCore.QRect(30, 105, 71, 23))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.lcdMatchedProcs.setFont(font)
        self.lcdMatchedProcs.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdMatchedProcs.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdMatchedProcs.setLineWidth(1)
        self.lcdMatchedProcs.setSmallDecimalPoint(True)
        self.lcdMatchedProcs.setDigitCount(6)
        self.lcdMatchedProcs.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdMatchedProcs.setProperty("value", 0.0)
        self.lcdMatchedProcs.setObjectName("lcdMatchedProcs")
        self.btnReloadMatchedProcs = QtGui.QPushButton(self.groupBox_6)
        self.btnReloadMatchedProcs.setEnabled(True)
        self.btnReloadMatchedProcs.setGeometry(QtCore.QRect(83, 130, 51, 23))
        self.btnReloadMatchedProcs.setObjectName("btnReloadMatchedProcs")
        self.label_28 = QtGui.QLabel(self.groupBox_6)
        self.label_28.setGeometry(QtCore.QRect(10, 110, 46, 13))
        self.label_28.setObjectName("label_28")
        self.btnHighlightAllProcs = QtGui.QPushButton(self.groupBox_6)
        self.btnHighlightAllProcs.setEnabled(True)
        self.btnHighlightAllProcs.setGeometry(QtCore.QRect(10, 130, 71, 23))
        self.btnHighlightAllProcs.setObjectName("btnHighlightAllProcs")
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(10, 160, 131, 16))
        self.label_24.setObjectName("label_24")
        self.listMatchedProcs = QtGui.QListWidget(self.groupBox_6)
        self.listMatchedProcs.setGeometry(QtCore.QRect(10, 180, 121, 71))
        self.listMatchedProcs.setObjectName("listMatchedProcs")
        self.btnShowProcsWithSim = QtGui.QPushButton(self.groupBox_6)
        self.btnShowProcsWithSim.setEnabled(True)
        self.btnShowProcsWithSim.setGeometry(QtCore.QRect(110, 106, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.btnShowProcsWithSim.setFont(font)
        self.btnShowProcsWithSim.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.btnShowProcsWithSim.setText("")
        self.btnShowProcsWithSim.setFlat(False)
        self.btnShowProcsWithSim.setObjectName("btnShowProcsWithSim")
        self.btnShowMatchedProcs = QtGui.QPushButton(self.groupBox_6)
        self.btnShowMatchedProcs.setEnabled(True)
        self.btnShowMatchedProcs.setGeometry(QtCore.QRect(110, 157, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.btnShowMatchedProcs.setFont(font)
        self.btnShowMatchedProcs.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.btnShowMatchedProcs.setText("")
        self.btnShowMatchedProcs.setFlat(False)
        self.btnShowMatchedProcs.setObjectName("btnShowMatchedProcs")
        self.tabWidgetVB.addTab(self.tab, "")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 731, 310))
        self.page_2.setObjectName("page_2")
        self.tabWidget = QtGui.QTabWidget(self.page_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 731, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowserAVScan = QtGui.QTextBrowser(self.tab_3)
        self.textBrowserAVScan.setGeometry(QtCore.QRect(6, 10, 711, 261))
        self.textBrowserAVScan.setObjectName("textBrowserAVScan")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textBrowserBehavior = QtGui.QTextBrowser(self.tab_4)
        self.textBrowserBehavior.setGeometry(QtCore.QRect(7, 10, 711, 261))
        self.textBrowserBehavior.setObjectName("textBrowserBehavior")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textBrowserPEInfo = QtGui.QTextBrowser(self.tab_5)
        self.textBrowserPEInfo.setGeometry(QtCore.QRect(7, 10, 711, 261))
        self.textBrowserPEInfo.setObjectName("textBrowserPEInfo")
        self.tabWidget.addTab(self.tab_5, "")
        self.toolBox.addItem(self.page_2, "")
        self.line = QtGui.QFrame(frmVirusBattle)
        self.line.setGeometry(QtCore.QRect(10, 400, 731, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lblStatus = QtGui.QLabel(frmVirusBattle)
        self.lblStatus.setGeometry(QtCore.QRect(10, 420, 731, 31))
        self.lblStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblStatus.setWordWrap(True)
        self.lblStatus.setObjectName("lblStatus")

        self.retranslateUi(frmVirusBattle)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        self.tabWidgetVB.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmVirusBattle)

    def retranslateUi(self, frmVirusBattle):
        frmVirusBattle.setWindowTitle(QtGui.QApplication.translate("frmVirusBattle", "Virus Battle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Register", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmVirusBattle", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRegister.setText(QtGui.QApplication.translate("frmVirusBattle", "Register", None, QtGui.QApplication.UnicodeUTF8))
        self.editName.setToolTip(QtGui.QApplication.translate("frmVirusBattle", "<html><head/><body><p>Full name</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.editName.setWhatsThis(QtGui.QApplication.translate("frmVirusBattle", "<html><head/><body><p>Fsasd</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.editEmail.setToolTip(QtGui.QApplication.translate("frmVirusBattle", "<html><head/><body><p>Email Address</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.editEmail.setWhatsThis(QtGui.QApplication.translate("frmVirusBattle", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmVirusBattle", "Email:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("frmVirusBattle", "Saved Profiles:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmVirusBattle", "Profile name:", None, QtGui.QApplication.UnicodeUTF8))
        self.editProfileName.setToolTip(QtGui.QApplication.translate("frmVirusBattle", "<html><head/><body><p>Email Address</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.editProfileName.setWhatsThis(QtGui.QApplication.translate("frmVirusBattle", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveProfile.setText(QtGui.QApplication.translate("frmVirusBattle", "Save ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveProfile.setText(QtGui.QApplication.translate("frmVirusBattle", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportProfile.setText(QtGui.QApplication.translate("frmVirusBattle", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImportProfile.setText(QtGui.QApplication.translate("frmVirusBattle", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Highlight", None, QtGui.QApplication.UnicodeUTF8))
        self.editHighlightCaption.setHtml(QtGui.QApplication.translate("frmVirusBattle", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">IDA Virus Battle Default Caption</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmVirusBattle", "Highlight Caption:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("frmVirusBattle", "Highlight Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHighlightColorChooser.setText(QtGui.QApplication.translate("frmVirusBattle", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveHighlights.setText(QtGui.QApplication.translate("frmVirusBattle", "Remove highlights", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Virus Battle", None, QtGui.QApplication.UnicodeUTF8))
        self.checkUpperHalf.setText(QtGui.QApplication.translate("frmVirusBattle", "Upper half", None, QtGui.QApplication.UnicodeUTF8))
        self.checkNoLibProc.setText(QtGui.QApplication.translate("frmVirusBattle", "Exclude library Procedures", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("frmVirusBattle", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmVirusBattle", "API Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.editAPIKey.setToolTip(QtGui.QApplication.translate("frmVirusBattle", "<html><head/><body><p>Email Address</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.editAPIKey.setWhatsThis(QtGui.QApplication.translate("frmVirusBattle", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShowAPIKey.setText(QtGui.QApplication.translate("frmVirusBattle", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.browserAboutUs.setHtml(QtGui.QApplication.translate("frmVirusBattle", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Virusbattle is a web service that analyses malware and other binaries with a variety of advanced static and dynamic analyses. For more information check out the </span><a href=\"http://ulsrl.org/project/VirusBattle/\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Lab Website</span></a><span style=\" font-size:8pt;\">.The Plugin is an integration of Virusbattle web service API into the well known IDA disassembler. </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("frmVirusBattle", "About:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageConfiguration), QtGui.QApplication.translate("frmVirusBattle", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("frmVirusBattle", "Uploaded binaries:", None, QtGui.QApplication.UnicodeUTF8))
        self.listBins.setToolTip(QtGui.QApplication.translate("frmVirusBattle", "List of binaries matched to the current binary", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBinary.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Binary", None, QtGui.QApplication.UnicodeUTF8))
        self.listChildren.setToolTip(QtGui.QApplication.translate("frmVirusBattle", "List of binaries matched to the current binary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("frmVirusBattle", "Upload Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("frmVirusBattle", "MD5:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("frmVirusBattle", "Class:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("frmVirusBattle", "File type:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDownloadBinary.setText(QtGui.QApplication.translate("frmVirusBattle", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("frmVirusBattle", "Children:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("frmVirusBattle", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefreshBinary.setText(QtGui.QApplication.translate("frmVirusBattle", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("frmVirusBattle", "SHA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("frmVirusBattle", "File Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupChild.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Child", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("frmVirusBattle", "Service Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("frmVirusBattle", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("frmVirusBattle", "Child Hash:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Unpacker", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("frmVirusBattle", "Message:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("frmVirusBattle", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDownloadChildBinary.setText(QtGui.QApplication.translate("frmVirusBattle", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReloadBinaries.setText(QtGui.QApplication.translate("frmVirusBattle", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("frmVirusBattle", "Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetVB.setTabText(self.tabWidgetVB.indexOf(self.tab_2), QtGui.QApplication.translate("frmVirusBattle", "Binaries", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("frmVirusBattle", "Matched binaries:", None, QtGui.QApplication.UnicodeUTF8))
        self.listMatchedBins.setToolTip(QtGui.QApplication.translate("frmVirusBattle", "List of binaries matched to the current binary", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBinary_2.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Matched Binary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("frmVirusBattle", "SHA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("frmVirusBattle", "Similarity:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDownloadMatchedBin.setText(QtGui.QApplication.translate("frmVirusBattle", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.lblOpenFileHash.setText(QtGui.QApplication.translate("frmVirusBattle", "Opened file hash:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Procedure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("frmVirusBattle", "Binary ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("frmVirusBattle", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("frmVirusBattle", "RVA:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkMatchedLeftProcIsThunk.setText(QtGui.QApplication.translate("frmVirusBattle", "Thunk", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("frmVirusBattle", "Code Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkMatchedLeftProcIsLib.setText(QtGui.QApplication.translate("frmVirusBattle", "Library", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("frmVirusBattle", "PE Segment:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("frmVirusBattle", "Semantic Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReloadSimilarBins.setText(QtGui.QApplication.translate("frmVirusBattle", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Matched Procedure", None, QtGui.QApplication.UnicodeUTF8))
        self.checkMatchedRightProcIsThunk.setText(QtGui.QApplication.translate("frmVirusBattle", "Thunk", None, QtGui.QApplication.UnicodeUTF8))
        self.checkMatchedRightProcIsLib.setText(QtGui.QApplication.translate("frmVirusBattle", "Library", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("frmVirusBattle", "Semantic Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("frmVirusBattle", "Code Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("frmVirusBattle", "RVA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("frmVirusBattle", "PE Segment:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("frmVirusBattle", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("frmVirusBattle", "Binary ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("frmVirusBattle", "Proc(RVA) with matches:", None, QtGui.QApplication.UnicodeUTF8))
        self.listProcsWithSim.setToolTip(QtGui.QApplication.translate("frmVirusBattle", "List of binaries matched to the current binary", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReloadMatchedProcs.setText(QtGui.QApplication.translate("frmVirusBattle", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("frmVirusBattle", "Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHighlightAllProcs.setText(QtGui.QApplication.translate("frmVirusBattle", "Highlight All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("frmVirusBattle", "Matched procs:", None, QtGui.QApplication.UnicodeUTF8))
        self.listMatchedProcs.setToolTip(QtGui.QApplication.translate("frmVirusBattle", "List of binaries matched to the current binary", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetVB.setTabText(self.tabWidgetVB.indexOf(self.tab), QtGui.QApplication.translate("frmVirusBattle", "Matches", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("frmVirusBattle", "VB", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("frmVirusBattle", "AVScan", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("frmVirusBattle", "Behavior", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("frmVirusBattle", "PE Info", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("frmVirusBattle", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("frmVirusBattle", "idle", None, QtGui.QApplication.UnicodeUTF8))

